name: On Main Merge
run-name: On Main Merge
on:
  push:
    branches:
      - main

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  ECR_REGISTRY: 117000019572.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: hello
  IMAGE_TAG: latest

jobs:
  container-build:
    name: Container Build
    runs-on: ubuntu-22.04
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - 
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - 
        name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG src/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  generate-sbom:
    needs: container-build
    name: Generate Container SBOM
    runs-on: ubuntu-22.04
    steps:
      - 
        uses: actions/checkout@v3
      -
        uses: snyk/actions/setup@master
      # - 
      #   name: Run Snyk to generate SBOM
      #   run: snyk sbom --format=cyclonedx1.4+json --json-file-output SBOM.json
      -
        name: Run Snyk to generate SBOM
        run: echo "Not available in Free Tier."

  deploy:
    needs: generate-sbom
    name: Redeploys the Pod using the latest image
    runs-on: ubuntu-22.04
    steps:
      -
        name: Deployment
        run: echo "To do."