name: On Pull Request
run-name: PR #${{ github.event.number }}
on: [pull_request, workflow_dispatch]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  application-assessment:
    name: Application Assessment
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./src
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Run Snyk to check for Open Source vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        with:
          args: --sarif-file-output=snyk.sarif
      - 
        name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-oss.sarif
      
  container-assessment:
    name: Container Assessment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Build the container image
      run: docker build -t raphabot/hello:test .
    - 
      name: Run Snyk to check container image for vulnerabilities
      continue-on-error: true # To make sure that SARIF upload gets called
      uses: snyk/actions/docker@master
      with:
        image: raphabot/hello:test
        args: --file=Dockerfile
    - 
      name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk-container.sarif
 
  kubernetes-artifact-assessment:
    name: Kubernetes Artifact Assessment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kube
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Run Snyk to check Kubernetes Artificat misconfigurations
        continue-on-error: true
        uses: snyk/actions/iac@master # To make sure that SARIF upload gets called
      - 
        name: Upload result to GitHub Code Scanning
        uses: github/github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-iac.sarif
