name: On Pull Request
run-name: PR #${{ github.event.number }}
on: [pull_request, workflow_dispatch]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  oss-assessment:
    permissions: write-all
    name: Open Source Assessment
    runs-on: ubuntu-22.04
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Run Snyk to check for Open Source vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          args: ./src
  
  code-assessment:
    needs: oss-assessment
    permissions: write-all
    name: SAST Assessment
    runs-on: ubuntu-22.04
    steps:
      - 
        uses: actions/checkout@v3
      -
        uses: snyk/actions/setup@master
      - 
        name: Run Snyk to check for Static Application Security Testing Findings
        continue-on-error: true
        run: snyk code test ./src
      
  container-assessment:
    needs: code-assessment
    permissions: write-all
    name: Container Assessment
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Build the container image
      run: docker build -t raphabot/hello:test src/
    - 
      name: Run Snyk to check container image for vulnerabilities
      # continue-on-error: true # To make sure that SARIF upload gets called
      uses: snyk/actions/docker@master
      with:
        image: raphabot/hello:test
        args: --severity-threshold=high --file=src/Dockerfile
 
  kubernetes-artifact-assessment:
    needs: container-assessment
    permissions: write-all
    name: Kubernetes Artifact Assessment
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Run Snyk to check Kubernetes Artificat misconfigurations
        continue-on-error: true # To make sure that SARIF upload gets called
        uses: snyk/actions/iac@master 
        with:
          args: ./kube
  
  terraform-assessment:
    needs: kubernetes-artifact-assessment
    permissions: write-all
    name: Terraform Assessment
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Run Snyk to check AWS misconfigurations in Terraform IaC
        continue-on-error: true # To make sure that SARIF upload gets called
        uses: snyk/actions/iac@master 
        with:
          args: cloud-infra/main.tf