name: On Pull Request
run-name: PR #${{ github.event.number }}
on: [pull_request, workflow_dispatch]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  application-assessment:
    permissions: write-all
    name: Application Assessment
    runs-on: ubuntu-22.04
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Run Snyk to check for Open Source vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        with:
          args: ./src --sarif-file-output=oss-and-code-snyk.sarif
      - 
        name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: oss-and-code-snyk.sarif
          category: oss-and-code
      
  container-assessment:
    permissions: write-all
    name: Container Assessment
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Build the container image
      run: docker build -t raphabot/hello:test src/
    - 
      name: Run Snyk to check container image for vulnerabilities
      continue-on-error: true # To make sure that SARIF upload gets called
      uses: snyk/actions/docker@master
      with:
        image: raphabot/hello:test
        args: --file=/src/Dockerfile --sarif-file-output=container-snyk.sarif
    - 
      name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: container-snyk.sarif
        category: container
 
  kubernetes-artifact-assessment:
    permissions: write-all
    name: Kubernetes Artifact Assessment
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        name: Run Snyk to check Kubernetes Artificat misconfigurations
        continue-on-error: true # To make sure that SARIF upload gets called
        uses: snyk/actions/iac@master 
        with:
          args: ./kube --sarif-file-output=k8s-snyk.sarif
      - 
        name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: k8s-snyk.sarif
          category: k8s-artificat
